### PR TITLE
Allow setting and reading individual Bitmap pixels

### PR DESCRIPTION
**Pull request by Nycto**
This change adds the ability to set and read individual pixels in a Bitmap. It adds a type called `BitmapView` that is supposed to represent any type that allows for this. Right now, that's just `DisplayFrame` and `BitmapData`

### CODE REVIEW

**Comment by samdze** [comment]
Forgot to review. Will do ASAP

**Comment by Nycto** [comment]
Any updates here?

**Comment by samdze** [comment]
Sorry! I'm quite busy in this period, will take the time to do it tomorrow

**Comment by Nycto** [comment]
No rush at all on this. I’ve got it checked out locally, so I am not at all blocked on anything here. And thank you!

**Comment by samdze** [comment]
Finally!
Thank you!

**Pull request merged**
