### PR TITLE
Dynamic PDX name

### LINKED ISSUE #28: Use `projectName()` instead of static PDX name?
👋 figured I'd start with some easy feedback. It's very possible I'm just missing something. Right now when I build, the output is a `playdate.pdx`. That means when I upload to device via the sim, other apps with that PDX name get overwritten.

It seems like this should be easy to change by updating the [`bundlePDX` build proc](https://github.com/samdze/playdate-nim/blob/c7d9bac47ff9337e35bbb09247fab0ad845e5eb7/src/playdate/build/nimble.nim#L13) to use `projectName()`:

``` nim
exec(pdcPath() & " --verbose -sdkpath " & sdkPath() & " source " & projectName())
```

This change seems to work well for me locally, but I'm not sure whether there's a specific reason it's set up like this, so I figured I'd open an issue instead of just PRing.

### PR DESCRIPTION
**Pull request by paulstraw**
Closes #28, see discussion there for details. Note the gitignore `build` change; pretty sure that wasn't intentional before, but lmk if you'd prefer a different solution (or feel free to change yourself if you prefer).

### CODE REVIEW

**Comment by samdze** [comment]
The `.gitignore` `build/` entry can probably be entirely removed.
It was a only valid in previous versions of the bindings.

Anyway, looks good!

**Comment by paulstraw** [comment]
Sweet, updated!

**Comment by samdze** [comment]
Thank you for your first contribution here!

**Comment by paulstraw** [comment]
No problem, happy I was able to help in a small way :)

**Pull request merged**
